// react-portfolio/src/Navbar.js
import React from 'react';
import logo from './Logo final.svg';
//import './App.css';
import './cascades/Navbar.css';
import NavbarLink from "./NavbarLink";
import LinkType from "./NavbarLink";

class Navbar extends React.Component{

render(){
return(
    <div className="Navbar">
        <ul className="Links">
            <a href = "fr4ct1ons.myportfolio.com"> <img src = {logo} className = "Logo"/></a>
            
            <NavbarLink name="ART GALLERY" linkType={2} pageLink = "https://fr4ct1ons.myportfolio.com/work"></NavbarLink>
            <NavbarLink name="WHO AM I" linkType={1} pageLink = "#"></NavbarLink>
            <NavbarLink name="GAMES" linkType={2} pageLink = "https://fr4ct1ons.myportfolio.com/full-gallery"></NavbarLink>
            <NavbarLink name="SOFTWARE" linkType={2} pageLink = "https://fr4ct1ons.myportfolio.com/software"></NavbarLink>

        </ul>
    </div>
)
}

}

export default Navbar

// svelte-portfolio/src/Navbar.svelte
<script>
        let src = "assets/Logo final.svg"
        import NavbarLink from "./NavbarLink.svelte"

</script>

<div class="Navbar">
    <ul class="Links">
        <a href = "fr4ct1ons.myportfolio.com"><img src={src} alt="FR4CT1ONS" class="Logo"></a>
        <NavbarLink name="ART GALLERY" linkType=LinkGallery pageLink = "https://fr4ct1ons.myportfolio.com/work" />
        <NavbarLink name="WHO AM I" linkType=LinkActive pageLink = "#"></NavbarLink>
        <NavbarLink name="GAMES" linkType=LinkGallery pageLink = "https://fr4ct1ons.myportfolio.com/full-gallery"></NavbarLink>
        <NavbarLink name="SOFTWARE" linkType=LinkGallery pageLink = "https://fr4ct1ons.myportfolio.com/software"></NavbarLink>

    </ul>
</div>

<style>
.Navbar
{
    background-color: rgb(70, 70, 70);
    overflow: hidden;
    padding: 14px;
    display: block;
    margin-bottom: 25px;
}

.Links
{
    list-style-type: none;
    margin: 0;
    height: 60px;
    padding: 0;
    overflow: hidden
}

.Links li
{
    float: right;
}

.Links li a
{
    display: block;
    margin: 8px;
    font-size: 200%;
    text-decoration: none;
}

.Logo
{
    height: 100%;
    float: left;
}
</style>
