// react-portfolio/src/Page.js
import React from 'react';
//import './App.css';
import './cascades/Navbar.css';

class Page extends React.Component{

render(){

return(
    <div style={{width: "70%"}, {textAlign: "center"}}>
        <div style={{width: "66%"}, {margin: "auto"}, {display: "block"} }>
            <h1 style={{color: "red"}}>{this.props.title}</h1>
            <h2 style={{color: "rgb(150, 150, 150)"}}><i>{this.props.subtitle}</i></h2>
        </div>
    </div>
)
}

}

export default Page

// svelte-portfolio/src/Page.svelte
<div class="Page">
    <h1>{title}</h1>
    <h2><i>{subtitle}</i></h2>
</div>
    
<script>
export let title = "Title"
export let subtitle = "Subtitle"
</script>

<style>
.Page
{
  width: 66%;
  margin: auto;
  display: block
}

.Page h1
{
  color: red;
}

.Page h2
{
  color: rgb(150, 150, 150)
}
.Page p
{
  color: white;
}
</style>
