// vue-portfolio/src/NavbarLink.vue
<template>
    <li><a v-on:click="ChangePage(index)" v-bind:class=linkType>{{name}}</a></li>
</template>


<script>
//v-bind:href=pageLink
export default {
    props: ["name", "linkType", "pageLink", "index"],
    data: function()
    {
        return {
            
        }
    },
    methods: 
    {
        ChangePage(index )
        {
            //alert(index);
            this.$emit("ChangePage", index)
        }
    }
}
</script>

<style>
.LinkActive
{
    color : rgb(255, 0, 0);
}

.LinkGallery
{
    color : rgb(220,85,220);
}

.LinkPage
{
    color : rgb(225,220,80);
}
</style>

// react-portfolio/src/NavbarLink.js
import React from 'react';
//import './App.css';
import './cascades/Navbar.css';

class NavbarLink extends React.Component{

render(){

    //alert(this.props.linkType)
    let newColor = "white";
    switch(this.props.linkType)
    {
        case 1:
            newColor = "rgb(255, 0, 0)";
            break;
        case 2:
            newColor = "rgb(220,85,220)";
            break;
        case 3:
            newColor = "rgb(225,220,80)";
            break;
    }


return(
    <li><a onClick={() => this.props.ChangePage(this.props.index)} href="#" style={{color : newColor}}>{this.props.name}</a></li>
)
}
}

export default NavbarLink

const LinkType = {
    CURRENT: "current",
    PAGE: "page",
    GALLERY: "gallery"
}
